# Use postgres/password user/password credentials
version: '3.1'
services:
  db:
    image: poc-postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: poc_test
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080